"use client";

import { Copy, FileText, LayoutPanelTop, ReceiptText, Settings2, SlidersHorizontal, TextCursorInput } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";

import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { useAuthStore } from "@/stores/auth-store";
import { updateDocumentSettings } from "@/utils/Apis";

type DocumentSettings = { prefix: string; separator: string; yearFormat: string; startNumber: string; padding: number; priceMode: "ht" | "ttc"; receiptWidth: "80" | "58"; totalHtLabel: string; totalVatLabel: string; netLabel: string; recipientSignature: string; amountPrefix: string; amountInWords: boolean; recipientSection: boolean; verticalLines: boolean; clientPosition: "right" | "left"; columns: Record<string, boolean>; paymentTerms: string; footer: string };

const defaults: DocumentSettings = { prefix: "FAC", separator: "/", yearFormat: "2026 (YYYY)", startNumber: "1", padding: 4, priceMode: "ht", receiptWidth: "80", totalHtLabel: "Total HT", totalVatLabel: "Total TVA", netLabel: "Net à Payer", recipientSignature: "", amountPrefix: "Arrêté le présent document à la somme de :", amountInWords: true, recipientSection: true, verticalLines: true, clientPosition: "right", columns: { "Réf": true, "Désignation": true, "Qté": true, "Unité": false, "P.U HT": true, "TVA": true, "Total HT": true }, paymentTerms: "50% à la commande 50% à la livraison", footer: "" };

function readSettings(value: string | null): DocumentSettings { try { return value ? { ...defaults, ...JSON.parse(value), columns: { ...defaults.columns, ...JSON.parse(value).columns } } : defaults; } catch { return defaults; } }

export default function DocumentStructureForm() {
  const company = useAuthStore();
  const [settings, setSettings] = useState<DocumentSettings>(() => readSettings(company.documentSettings));
  const [isSaving, setIsSaving] = useState(false);
  useEffect(() => setSettings(readSettings(company.documentSettings)), [company.documentSettings]);
  const update = <K extends keyof DocumentSettings>(key: K, value: DocumentSettings[K]) => setSettings((current) => ({ ...current, [key]: value }));
  const preview = `${settings.prefix}${settings.separator}${settings.yearFormat.slice(0, 4)}${settings.separator}${settings.startNumber.padStart(settings.padding, "0")}`;

  async function save() { setIsSaving(true); try { await updateDocumentSettings(JSON.stringify(settings)); toast.success("Configuration des documents enregistrée"); } catch (error) { toast.error(error instanceof Error ? error.message : "Une erreur s'est produite"); } finally { setIsSaving(false); } }

  return <div className="space-y-4">

    <SectionCard icon={<SlidersHorizontal className="size-4" />} title="Mode d’affichage des prix" description="Choisissez si vos tableaux PDF affichent les prix unitaires en Hors Taxe (HT) ou Tout Compris (TTC)."><ChoiceGrid value={settings.priceMode} onChange={(value) => update("priceMode", value as "ht" | "ttc")} choices={[{ value: "ht", title: "Mode Classique (HT)", detail: "Affiche P.U. HT et Total HT dans le tableau avec calcul TVA au récapitulatif. Recommandé B2B." }, { value: "ttc", title: "Mode Simplifié (TTC)", detail: "Affiche directement les montants Toutes Taxes Comprises (TTC) par article. Idéal pour particuliers." }]} /></SectionCard>
    <SectionCard icon={<ReceiptText className="size-4" />} title="Format Imprimante Thermique (Ticket de Caisse)" description="Définissez la largeur de rouleau par défaut pour vos tickets de caisse."><ChoiceGrid value={settings.receiptWidth} onChange={(value) => update("receiptWidth", value as "80" | "58")} choices={[{ value: "80", title: "80 mm (Standard POS)", detail: "Rouleau 3 pouces — standard pour imprimantes de caisse fixes." }, { value: "58", title: "58 mm (Compact POS)", detail: "Rouleau 2 pouces — idéal pour les imprimantes portables." }]} /></SectionCard>
    <SectionCard icon={<TextCursorInput className="size-4" />} title="Libellés personnalisés" description="Personnalisez les intitulés de totaux, signatures et phrases de clôture."><div className="grid gap-3 sm:grid-cols-3"><MiniInput label="Libellé total HT" value={settings.totalHtLabel} onChange={(value) => update("totalHtLabel", value)} /><MiniInput label="Libellé total TVA" value={settings.totalVatLabel} onChange={(value) => update("totalVatLabel", value)} /><MiniInput label="Libellé net à payer" value={settings.netLabel} onChange={(value) => update("netLabel", value)} /><MiniInput label="Signature destinataire" value={settings.recipientSignature} onChange={(value) => update("recipientSignature", value)} /><div className="sm:col-span-2"><MiniInput label="Préfixe montant en lettres" value={settings.amountPrefix} onChange={(value) => update("amountPrefix", value)} /></div></div></SectionCard>
    <SectionCard icon={<LayoutPanelTop className="size-4" />} title="Options de Mise en Page & Affichage" description="Activez ou masquez des blocs complémentaires sur vos impressions PDF."><div className="space-y-2"><ToggleRow label="Montant en toutes lettres" description="Affiche la somme totale écrite en lettres en bas du document." checked={settings.amountInWords} onChange={(value) => update("amountInWords", value)} /><ToggleRow label="Section Signature Destinataire" description="Affiche un encadré pour le visa et la signature du client." checked={settings.recipientSection} onChange={(value) => update("recipientSection", value)} /><ToggleRow label="Lignes verticales du tableau" description="Affiche des séparateurs verticaux entre les colonnes du tableau." checked={settings.verticalLines} onChange={(value) => update("verticalLines", value)} /><div className="rounded-xl border border-slate-200 p-3"><p className="text-[10px] font-bold text-slate-800">Position de l’encadré du Client</p><p className="mt-0.5 text-[9px] text-slate-500">Alignez les coordonnées du client à droite (standard) ou à gauche.</p><div className="mt-3 grid grid-cols-2 gap-2">{(["right", "left"] as const).map((position) => <button key={position} type="button" onClick={() => update("clientPosition", position)} className={`rounded-lg border py-2 text-[10px] font-semibold ${settings.clientPosition === position ? "border-primary bg-primary/5 text-primary" : "border-slate-200 text-slate-600"}`}>{position === "right" ? "À droite (Standard)" : "À gauche"}</button>)}</div></div></div></SectionCard>
    <SectionCard icon={<FileText className="size-4" />} title="Colonnes du Tableau PDF" description="Organisez, réordonnez et renommez les colonnes de vos devis et factures."><div className="space-y-2">{Object.entries(settings.columns).map(([column, visible]) => <div key={column} className="flex items-center gap-3 rounded-xl border border-slate-200 px-3 py-2"><span className="text-slate-400">↕</span><span className="flex-1 rounded-md border border-dashed border-slate-200 px-2 py-1 text-[10px] font-semibold text-slate-700">{column}</span><span className={`text-[9px] font-semibold ${visible ? "text-primary" : "text-slate-400"}`}>{visible ? "Affichée" : "Masquée"}</span><Switch checked={visible} onChange={(value) => update("columns", { ...settings.columns, [column]: value })} /></div>)}</div></SectionCard>
    <SectionCard icon={<ReceiptText className="size-4" />} title="Pied de page & Conditions de Règlement" description="Définissez les conditions générales de vente et les mentions légales par défaut."><div className="space-y-3"><MiniInput label="Conditions de paiement par défaut" value={settings.paymentTerms} onChange={(value) => update("paymentTerms", value)} /><label className="grid gap-1 text-[9px] font-bold uppercase tracking-wide text-slate-700">Notes et mentions de bas de page<Textarea value={settings.footer} onChange={(event) => update("footer", event.target.value)} className="min-h-20 rounded-xl border-slate-200 text-xs font-normal normal-case" placeholder="Vos mentions légales, coordonnées bancaires et conditions…" /></label></div></SectionCard>
    <button type="button" onClick={save} disabled={isSaving} className="ml-auto block rounded-lg bg-primary px-4 py-2 text-xs font-semibold text-primary-foreground disabled:opacity-60">{isSaving ? "Enregistrement…" : "Enregistrer la configuration"}</button>
  </div>;
}

function SectionCard({ icon, title, description, children }: { icon: React.ReactNode; title: string; description: string; children: React.ReactNode }) { return <Card className="rounded-[22px] border-slate-200 px-5 py-5 shadow-sm"><div className="flex gap-3 border-b border-slate-100 pb-4"><span className="flex size-7 items-center justify-center rounded-xl bg-primary/10 text-primary">{icon}</span><div><h2 className="text-sm font-bold text-slate-900">{title}</h2><p className="mt-0.5 text-[9px] text-slate-500">{description}</p></div></div><div className="pt-4">{children}</div></Card>; }
function MiniInput({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="grid gap-1 text-[9px] font-bold uppercase tracking-wide text-slate-700">{label}<Input value={value} onChange={(event) => onChange(event.target.value)} className="h-8 rounded-lg border-slate-200 text-xs font-normal normal-case shadow-none" /></label>; }
function Switch({ checked, onChange }: { checked: boolean; onChange: (value: boolean) => void }) { return <button type="button" aria-pressed={checked} onClick={() => onChange(!checked)} className={`relative h-5 w-8 rounded-full transition-colors ${checked ? "bg-primary" : "bg-slate-200"}`}><span className={`absolute top-0.5 size-4 rounded-full bg-white transition-transform ${checked ? "translate-x-3.5" : "translate-x-0.5"}`} /></button>; }
function ToggleRow({ label, description, checked, onChange }: { label: string; description: string; checked: boolean; onChange: (value: boolean) => void }) { return <div className="flex items-center gap-3 rounded-xl border border-slate-200 px-3 py-3"><span className="flex-1"><span className="block text-[10px] font-bold text-slate-800">{label}</span><span className="block text-[9px] text-slate-500">{description}</span></span><Switch checked={checked} onChange={onChange} /></div>; }
function ChoiceGrid({ value, onChange, choices }: { value: string; onChange: (value: string) => void; choices: { value: string; title: string; detail: string }[] }) { return <div className="grid gap-3 sm:grid-cols-2">{choices.map((choice) => <button type="button" key={choice.value} onClick={() => onChange(choice.value)} className={`rounded-xl border p-4 text-left ${value === choice.value ? "border-primary bg-primary/5" : "border-slate-200"}`}><span className="flex items-center justify-between text-[10px] font-bold text-slate-800">{choice.title}{value === choice.value && <span className="flex size-4 items-center justify-center rounded-full bg-primary text-[9px] text-white">✓</span>}</span><span className="mt-1 block text-[9px] leading-4 text-slate-500">{choice.detail}</span></button>)}</div>; }
