export const Options ={
    "LOW":"FAIBLE",
    "MEDIUM":"MOYEN",
    "HIGH":"ÉLEVÉ",
    "URGENT":"URGENT",
    "NEW":"NOUVEAU",
    "CONTACTED":"CONTACTÉ",
    "QUALIFIED":"QUALIFIÉ",
    "QUOTE_TO_PREPARE":"DEVIS À PRÉPARER",
    "QUOTE_SENT":"DEVIS ENVOYÉ",
    "NEGOTIATION":"NÉGOCIATION",
    "WON":"GAGNÉ",
    "LOST":"PERDU",
    "FOLLOW_UP_LATER":"SUIVI ULTÉRIEUR",
    "ACTIVE":"ACTIF",
    "GOOD_CLIENT":"BON CLIENT",
    "TO_MONITOR":"À SURVEILLER",
    "INACTIVE":"INACTIF",
    "BLOCKED":"BLOQUÉ",
    "PHONE":"TÉLÉPHONE",
    "WHATSAPP":"WHATSAPP",
    "FACEBOOK":"FACEBOOK",
    "INSTAGRAM":"INSTAGRAM",
    "WEBSITE":"SITE WEB",
    "TIKTOK":"TIKTOK",
    "LINKEDIN":"LINKEDIN",
    "VISIT":"VISITE",
    "REFERRAL":"PARRAINAGE",
    "OTHER":"AUTRE",
    "INDIVIDUAL":"PARTICULIER",
    "FARMER":"AGRICULTEUR",
    "COMPANY":"ENTREPRISE",
    "RESELLER":"REVENDEUR",
    "ADMINISTRATION":"ADMINISTRATION",
    "ASSOCIATION":"ASSOCIATION",
    BROUILLON: "Brouillon",
    ENVOYE: "Envoyé",
    PAYE: "Payé",
    ANNULE: "Annulé",
}

export const fieldLabels = {
  reference:"Référence",  
  type: "Type",
  status: "Statut",
  companyType: "Type d’entreprise",
  companyName: "Nom de l’entreprise",
  fullName: "Nom complet",
  email: "E-mail",
  phone: "Téléphone",
  whatsapp: "WhatsApp",
  website: "Site web",
  address: "Adresse",
  city: "Ville",
  region: "Région",
  country: "Pays",
  ice: "ICE",
  rc: "RC",
  ifNumber: "Identifiant fiscal (IF)",
  source: "Source",
  priority: "Priorité",
  notes: "Notes",
  nextFollowUpAt: "Prochaine relance",
  createdAt: "Date de création",
};